{"timestamp":"2025-08-03T08:33:18.844401","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-03T08:33:18.844856","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/daily_snapshot_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-03T08:33:18.862187Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-03T08:33:18.862412Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-03T08:33:18.862467Z","level":"info","event":"Current task name:save_snapshot","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-03T08:33:18.862621Z","level":"info","event":"Dag name:daily_snapshot_dag","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-03T08:33:18.864954","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OperationalError","exc_value":"connection to server at \"postgres\" (172.19.0.3), port 5432 failed: FATAL:  password authentication failed for user \"amithnair\"\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":877,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1164,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/daily_snapshot_dag.py","lineno":8,"name":"save_daily_snapshot"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py","lineno":122,"name":"connect"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-03T08:33:18.865562Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-03T08:33:18.865715Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-03T08:33:18.865797Z","level":"info","event":"Task:<Task(PythonOperator): save_snapshot>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-03T08:33:18.865843Z","level":"info","event":"Failure caused by connection to server at \"postgres\" (172.19.0.3), port 5432 failed: FATAL:  password authentication failed for user \"amithnair\"","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-03T08:33:18.865897Z","level":"info","event":"","chan":"stdout","logger":"task"}
